spring.application.name=notification-service

spring.mongodb.uri=${MONGO_URI}

spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USER}
spring.rabbitmq.password=${RABBITMQ_PASS}

jwt.secret=${JWT_SECRET}